on:
  push:
    paths:
      - "tutorial/retrospectives/**/*.yaml"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: oss-gate/issue-cleaner@v3
        with:
          author: ${{ github.event.sender.login }}
